config/routes.rb
Earlyvoter::Application.routes.draw do
  resources :voters
  root :to => 'voters#new'
  
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  attr_accessible :voter_name, :street_address, :city, :state, :zipcode, :email, :phone, :lat, :lng, :gmaps
  
  acts_as_gmappable :lat => "lat", :lng => "lng"
  # build an address from street, city, and state attributes
  geocoded_by :gmaps4rails_address

  # store the fetched address in the full_address attribute
  reverse_geocoded_by :lat, :lng, :address => :gmaps4rails_address

  validates :voter_name, :presence => true
  validates :street_address, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :zipcode, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true

  def gmaps4rails_address
  #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.street_address}, #{self.city}, #{self.state}, #{self.zipcode}" 
  end
  
  def gmaps4rails_marker_picture
    {
     "picture" => "http://media.roryreid.com.s3.amazonaws.com/house-image.png",
     "width" => 32,
     "height" => 32,
     "marker_anchor" => [ 5, 10],
     "shadow_picture" => "/images/morgan.png" ,
     "shadow_width" => "110",
     "shadow_height" => "110",
     "shadow_anchor" => [5, 10],
    }
  end
  
  def gmaps4rails_infowindow
      "You are here:<br>#{self.street_address}<br>#{self.city}, #{self.state} #{self.zipcode}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  # GET /voters
  # GET /voters.json
  def index
    @voters = Voter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voters }
    end
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
    @voter = Voter.find(params[:id])
    @json = @voter.to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voter }
    end
  end

  # GET /voters/new
  # GET /voters/new.json
  def new
    @voter = Voter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voter }
    end
  end

  # GET /voters/1/edit
  def edit
    @voter = Voter.find(params[:id])
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(params[:voter])

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Found your early vote locations.' }
        format.json { render json: @voter, status: :created, location: @voter }
      else
        format.html { render action: "new" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voters/1
  # PUT /voters/1.json
  def update
    @voter = Voter.find(params[:id])

    respond_to do |format|
      if @voter.update_attributes(params[:voter])
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy

    respond_to do |format|
      format.html { redirect_to voters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Earlyvoter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Earlyvoter</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Find EV location", "/voters/new"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
		<%= yield :scripts %>
  </body>
</html>

app/views/voters/_form.html.erb
<%= form_for @voter, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :voter_name, "Name", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :voter_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :street_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zipcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zipcode, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Find Now", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                voters_path, :class => 'btn' %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<%- model_class = @voter.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/voters/index.html.erb
<%- model_class = Voter.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:voter_name) %></th>
      <th><%= model_class.human_attribute_name(:street_address) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:zipcode) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:lat) %></th>
      <th><%= model_class.human_attribute_name(:lng) %></th>
      <th><%= model_class.human_attribute_name(:gmaps) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @voters.each do |voter| %>
      <tr>
        <td><%= link_to voter.id, voter_path(voter) %></td>
        <td><%= voter.voter_name %></td>
        <td><%= voter.street_address %></td>
        <td><%= voter.city %></td>
        <td><%= voter.state %></td>
        <td><%= voter.zipcode %></td>
        <td><%= voter.email %></td>
        <td><%= voter.phone %></td>
        <td><%= voter.lat %></td>
        <td><%= voter.lng %></td>
        <td><%= voter.gmaps %></td>
        <td><%=l voter.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_voter_path(voter), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      voter_path(voter),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_voter_path,
            :class => 'btn btn-primary' %>

app/views/voters/new.html.erb
<%- model_class = @voter.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Find your voting location") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/voters/show.html.erb
<%- model_class = @voter.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Early vote locations nearby" %></h1>
</div>
<%= gmaps({
	:kml => {:data => '[ { url: "http://media.roryreid.com.s3.amazonaws.com/kml_finish/October-18.kml",
	                                options: {clickable: true } }]' },
    "map_options" => { "type" => "ROADMAP", "auto_adjust" => false, "auto_zoom" => false, "center_longitude" => @voter.lng, "center_latitude" => @voter.lat, "zoom" => 15 },
    "markers"     => { "data" => @json }
		
})
%>